variables:
  project:  './Rockstar.Generator/Rockstar.Generator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

trigger: 
  branches:
    include:
    - master

pr: none

steps:

- checkout: self

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 5.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration) /p:Version=1.0.$(build.buildId)'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packagesToPack: '$(project)'
    versioningScheme: 'off'
    buildProperties: 'Version="1.0.$(build.buildId)"'

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Rockstar.Generator.1.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'
